# Generated by Django 4.1.5 on 2024-08-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
