# Generated by Django 5.0 on 2024-08-31 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced')], max_length=50)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('family_type', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('number_of_siblings', models.IntegerField()),
                ('number_of_siblings_married', models.IntegerField()),
                ('sibling_details', models.TextField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_type', models.CharField(max_length=50)),
                ('complexion', models.CharField(max_length=50)),
                ('disabilities', models.TextField()),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerExpectations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matrimony.userprofile')),
            ],
        ),
    ]
