# Generated by Django 5.0 on 2024-09-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerexpectations',
            name='caste',
            field=models.CharField(choices=[('Caste 1', 'Caste 1'), ('Caste 2', 'Caste 2'), ('Caste 3', 'Caste 3')], default='Caste 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerexpectations',
            name='education',
            field=models.CharField(choices=[('High School', 'High School'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('PhD', 'PhD')], default='High School', max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerexpectations',
            name='location',
            field=models.CharField(choices=[('Location 1', 'Location 1'), ('Location 2', 'Location 2'), ('Location 3', 'Location 3')], default='Location 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerexpectations',
            name='occupation',
            field=models.CharField(choices=[('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Manager', 'Manager')], default='Engineer', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='body_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='caste',
            field=models.CharField(choices=[('Caste 1', 'Caste 1'), ('Caste 2', 'Caste 2'), ('Caste 3', 'Caste 3')], default='Caste 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='complexion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(choices=[('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Manager', 'Manager')], default='Engineer', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disabilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(choices=[('High School', 'High School'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('PhD', 'PhD')], default='High School', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(choices=[('Location 1', 'Location 1'), ('Location 2', 'Location 2'), ('Location 3', 'Location 3')], default='Location 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced')], default='Single', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number_of_siblings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number_of_siblings_married',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Other', 'Other')], default='Hindu', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sibling_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
