# Generated by Django 5.0 on 2024-09-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0003_alter_userprofile_annual_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='family_name',
        ),
    ]
