# Generated by Django 5.0 on 2024-09-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_remove_userprofile_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
